### ISSUE TITLE
Possible auth issue

### ISSUE THREAD

**Issue by gregdskb** [anecdotes-ai/remote-workflow-control#4]
Hi @Ido-Ozeri, Sorry to be a pain but I'm getting 404 from `curl` when trying to auth between two different repositories in the same organisation as a GitHub App. Works fine triggering a test workflow using a basic `curl` test workflow hitting the API so I think it must be auth.

```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event"
}
```
```
curl exit code: 404
[remote-workflow-control.sh][DEBUG]: POST request JSON data: {"ref": "main", "inputs": {"trigger_uuid": "934a9e35aa877e1e24fad49a"}}
```

**Comment by gregdskb** [comment]
README says `GITHUB_KEY`. Not sure what that is expected to be. For use with GitHub App I am generating a `GITHUB_TOKEN` from the App ID and private key and passing that

```
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACCESS_APPID }}
          private_key: ${{ secrets.ACCESS_PRIVATEKEY }}
```

Example: (Soz. URL redacted)

```
      - name: API Call
        id: api_call
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/****/****/actions/workflows/gitCloneTest.yml/dispatches \
          -d '{"ref":"main"}'

```
